name: CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      REMOTE_RUN: true
      ENVIRONMENT: "Prod"
      BROWSER: "Chrome"
      TEST_RESULTS: "TestResults"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
          
      - name: Install Chrome 
        run: sudo apt-get install google-chrome-stable

      - name: Create test results folder
        run: |
          mkdir -p ${{ env.TEST_RESULTS }}
          chmod 777 ${{ env.TEST_RESULTS }}
          
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: 9.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build -c Release --no-restore

      - name: Run the tests
        run: dotnet test --logger "html;LogFileName=NUnitTestResults.html" --results-directory ${{ env.TEST_RESULTS }}
        continue-on-error: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ${{ env.TEST_RESULTS }}
