name: CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      REMOTE_RUN: true
      ENVIRONMENT: "Prod"
      BROWSER: "Chrome"

    steps:
      # Repository
      - uses: actions/checkout@v4
        with:
          ref: develop
          
      - name: Install Chrome 
        run: sudo apt-get install google-chrome-stable

      # NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: 9.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build -c Release --no-restore

      - name: Run the tests
        run: dotnet test --logger "trx;LogFileName=testResults.trx"

      # Upload artifacts

      - name: Upload trx file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: testResults
          path: testResults.trx
